# Generated by Django 5.1.1 on 2024-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0009_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fichier', models.FileField(upload_to='ebooks/')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
